// JS EXECUTION CONTEXT 

// JS IS A SINGLE THREADED  LANGUAGE, WHICH MEANS IT ONLY HAS ONE CALL STACK AT ANY GIVEN TIME.
// THE CALL STACK KEEPS TRACK OF ALL FUNCTIONS THAT GET CALLED DURING THE PROGRAM'S EXECUTION.
